---
book_repo: pivotal-cf/docs-book-pks
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: "master"
feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-pks
    ref: "1.11"
  directory: tkgi/1-11
  subnav_template: pks_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: "v1.11"
    changelog_href: https://docs.pivotal.io/tkgi/1-11/release-notes.html
    local_header_img: /images/pks.png
    local_header_title: Tanzu Kubernetes Grid Integrated Edition
    search_placeholder: "Search TKGI v1.11"
    url_prefix: tkgi/1-11
    local_product_version: "1.11"
    local_header_links: []
    local_header_version_list:
      - url_prefix: https://docs.pivotal.io/tkgi/1-10
        display_name: v1.10
      - url_prefix: https://docs.pivotal.io/tkgi/1-9
        display_name: v1.9
      - url_prefix: https://docs.pivotal.io/tkgi/1-8
        display_name: v1.8
      - url_prefix: https://docs.pivotal.io/pks/1-7
        display_name: v1.7
      - url_prefix: https://docs.pivotal.io/pks/1-6
        display_name: v1.6
      - url_prefix: https://docs.pivotal.io/pks/1-5
        display_name: v1.5
      - url_prefix: https://docs.pivotal.io/pks/1-4
        display_name: v1.4
      - url_prefix: https://docs.pivotal.io/pks/1-3
        display_name: v1.3
      - url_prefix: https://docs.pivotal.io/pks/1-2
        display_name: v1.2
      - <a href="https://docs.pivotal.io/archives/pks-1-1.pdf">v1.1</a>
      - <a href="https://docs.pivotal.io/archives/pks-docs-1.0.pdf">v1.0</a>

# cross-product resources

- repository:
    name: pivotal-cf/docs-partials
    ref: master
  directory: pcf
  no_docs: true

book_title: VMware Tanzu™ Kubernetes Grid™ Integrated Edition
